### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by tsdgeos** [comment]
bot, build

**Comment by travier** [comment]
We need to remove the screenshot dimensions from the Appdata & submit that upstream. Weird that this hasn't been submitted already.

**Comment by flyingcakes85** [comment]
> We need to remove the screenshot dimensions from the Appdata & submit that upstream. Weird that this hasn't been submitted already.

I submitted it on Mar 12. [Link](https://invent.kde.org/network/falkon/-/merge_requests/31)

Patch is there in this repository. [Link](https://github.com/flathub/org.kde.falkon/blob/master/0001-Remove-screenshot-dimensions-from-appdata.patch)

Patch was removed in this PR by @tsdgeos if I'm right.

**Comment by travier** [comment]
Well, it's not in the 22.04 branch so we should keep it for now: https://invent.kde.org/network/falkon/-/commits/release/22.04/linux/appdata/org.kde.falkon.appdata.xml

**Comment by travier** [comment]
bot, build

**Pull request merged**
